bird_controller_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # root route
    path('', views.home, name='home'),
    # birds index view
    path('birds/', views.birds_index, name='index'),
    # birds detail view
    path('birds/<int:bird_id>/', views.birds_detail, name='detail'),
    # birds new view
    path('birds/new/', views.new_bird, name='new_bird'),
    # new sighting view
    path('birds/<int:bird_id>/new_sighting/', views.new_sighting, name='new_sighting'),
    # associate/remove association between bird, nest material
    path('birds/<int:bird_id>/assoc_nest/<int:nest_material_id>/', views.assoc_nest, name='assoc_nest'),
]

main_app/models.py
from django.db import models


# many-to-many relationship model
class NestMaterial(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name    


class Bird(models.Model):
    name = models.CharField(max_length=100)
    size = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    # make many-to-many association with NestMaterial
    nest_materials = models.ManyToManyField(NestMaterial)
    
    def __str__(self):
        return self.name


# one-to-many relationship model
class Sighting(models.Model):
    date = models.DateField('Date Seen')
    location = models.CharField(max_length=100)
    notes = models.TextField(max_length=300)

    # define relationship to Bird using foreign key
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"Sighting on {self.date}"

    class Meta:
        # sort by most recent date
        ordering = ['-date']

main_app/forms.py
from django import forms
from .models import Bird, Sighting, NestMaterial

# make a form based off of Bird model
class BirdForm(forms.ModelForm):
    # use Meta class
    class Meta:
        model = Bird
        fields = ['name', 'size', 'description']

    
class SightingForm(forms.ModelForm):
    date = forms.DateField(widget=forms.SelectDateWidget())
    class Meta:
        model = Sighting
        fields = ['date', 'location', 'notes']


class NestMaterialForm(forms.ModelForm):
    class Meta:
        model = NestMaterial
        fields = ['name']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Bird, Sighting, NestMaterial
from .forms import BirdForm, SightingForm, NestMaterialForm

# class Bird:
#     def __init__(self, name, size, description):
#         self.name = name
#         self.size = size
#         self.description = description

# birds = [
#     Bird('House Finch', 'small', 'loves sunflower seeds, males are red'),
#     Bird('Dark Eyed Junco', 'small', 'scurries around the ground, eats millet, digs with its feet'),
# ]

# Create your views here.
def home(request):
    template = 'index.html'
    return render(request, template)

def birds_index(request):
    template = 'birds/index.html'
    birds = Bird.objects.all()
    context = {'birds': birds}
    return render(request, template, context)

def birds_detail(request, bird_id):
    """Show Bird detail page"""
    # find bird by id
    bird = Bird.objects.get(id=bird_id)
    # show all nest materials that bird doesn't have
    materials_values_list = bird.nest_materials.all().values_list('id')
    unused_materials = NestMaterial.objects.exclude(id__in=materials_values_list)
    print('unused', unused_materials)
    # make the new sighting form available
    form = SightingForm()
    template = 'birds/detail.html'
    context = {
        'bird': bird,
        'form': form,
        'unused_materials': unused_materials,
        }
    return render(request, template, context)

def new_bird(request):
    """Add a new Bird"""
    # handle type of request
    # if a POST request is made
    if request.method == 'POST':
        # save the form data to database
        form = BirdForm(request.POST)
        if form.is_valid():
            # create new instance of bird
            bird = form.save()
            return redirect('detail', bird_id=bird.id)
    # if a GET request is made
    else:
        # render the form
        form = BirdForm()
        template = 'birds/new.html'
        context = {'form': form}
        return render(request, template, context)

def new_sighting(request, bird_id):
    """Add a new Sighting to a Bird"""
    form = SightingForm(request.POST)
    if form.is_valid():
        # assign bird_id to sighting, then save
        new_sighting = form.save(commit=False)
        new_sighting.bird_id = bird_id
        new_sighting.save()
    # redirect to bird's detail page
    return redirect('detail', bird_id=bird_id)

def assoc_nest(request, bird_id, nest_material_id):
    """Associate or remove association between Bird and Nest Materials"""
    bird = Bird.objects.get(id=bird_id)
    nest_material = NestMaterial.objects.get(id=nest_material_id)
    print('nest material', nest_material)
    # check if Add or Remove button was clicked
    if request.POST.get('add_nest_material'):
        print('add')
        bird.nest_materials.add(nest_material)
    elif request.POST.get('remove_nest_material'):
        print('remove')
        bird.nest_materials.remove(nest_material)
    # redirect back to bird details page
    return redirect('detail', bird_id=bird_id)

main_app/templates/base.html
<!--Load static files-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--Bootstrap CSS-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!--Custom CSS-->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Bird Collector</title>
</head>
<body>
<!--Navbar-->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Bird Collector</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapseLinks"
    aria-controls="collapseLinks" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="collapseLinks">
    <ul class="navbar-nav ml-auto">
      {% block nav_content %}   
      {% include 'nav.html' %}
      {% endblock %}
    </ul>
  </div>
</nav>

  {% block content %}
  {% endblock %}
  
<!--Bootstrap JS-->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

main_app/templates/birds/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Bird Details</h1>
    <div class="row">
      <div class="col">
        <!--Bird info-->
        <div class="card">
          <h3>{{ bird.name }}</h3>
          <p>Size: {{ bird.size }}</p>
          <p>Description: {{ bird.description }}</p>
        </div>
        <!--Sightings-->
        {% for sighting in bird.sighting_set.all %}
        <div class="card">
          <p>Date: {{ sighting.date }}</p>
          <p>Location: {{ sighting.location }}</p>
          <p>Notes: {{ sighting.notes }}</p>
        </div>
        {% endfor %}
      </div>
      <div class="col">
        <!--Sighting Form-->
        <div> 
          <form action="{% url 'new_sighting' bird.id %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Submit</button>
          </form>
        </div>
      </div>
    </div>
    <div class="row">
      <!--Nest Materials that Bird has-->
      <div class="col-6">
        {% if bird.nest_materials.count %}
          {% for material in bird.nest_materials.all %}
          <div class="card square">
            <h5>{{ material.name }}</h5>
            <form action="{% url 'assoc_nest' bird.id material.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" name="remove_nest_material" value="remove_nest_material">Remove</button>
            </form>
          </div>
          {% endfor %}
        {% else %}
          <h3>{{ bird.name }} is not building a nest right now</h3>
        {% endif %}
      </div>
      <!--Nest Materials that Bird Doesn't Have-->
      <div class="col-6">
        {% if unused_materials.count %}
          {% for material in unused_materials.all %}
          <div class="card square">
            <h5>{{ material.name }}</h5>
            <form action="{% url 'assoc_nest' bird.id material.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" name="add_nest_material" value="add_nest_material">Add</button>
            </form>
          </div>
          {% endfor %}
        {% else %}
          <h3>{{ bird.name }} used all the nest materials</h3>
        {% endif %}
      </div>
    </div>
</div>

{% endblock %}

main_app/templates/birds/index.html
{% extends 'base.html' %}
{% block content %}

<h1>All Birds!</h1>

{% endblock %}

main_app/templates/birds/new.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <h1>New Bird</h1>
  <form method="POST">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        <br/>
        {{field}}
      </div>
      {% endfor %}
      <button class="btn btn-primary" type="submit">Submit</button>
  </form>
</div>

{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <h1>Welcome to Bird Collector</h1>
  A Django Application
</div>

{% endblock %}

main_app/templates/nav.html
{% block nav_content %}
  <li class="nav-item active">
    <a class="nav-link" href="/admin/">Admin</a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'index' %}">Birds</a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'new_bird' %}">New Bird</a>
  </li>
{% endblock %}